version: '3.9'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: multibank-automation:latest
    environment:
      - CI=true
      - BASE_URL=${BASE_URL:-https://mb.io/en-AE}
    volumes:
      - ./reports:/app/reports
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    command: ["npx", "playwright", "test"]
